# Generated by Django 5.2.17 on 2026-09-11 22:57

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer_code', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('address2', models.CharField(blank=True, max_length=255)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('county', models.CharField(blank=True, max_length=100)),
                ('state', models.CharField(max_length=2)),
                ('zipcode', models.CharField(max_length=10)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('location_accuracy', models.CharField(blank=True, choices=[('street', 'Street'), ('zip', 'ZIP')], max_length=10)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customers', to='accounts.tenant')),
            ],
            options={
                'indexes': [models.Index(fields=['tenant', 'state'], name='customer_tenant_state_idx'), models.Index(fields=['tenant', 'county'], name='customer_tenant_county_idx'), models.Index(fields=['tenant', 'city'], name='customer_tenant_city_idx'), models.Index(fields=['tenant', 'zipcode'], name='customer_tenant_zip_idx')],
                'constraints': [models.UniqueConstraint(fields=('tenant', 'customer_code'), name='unique_tenant_customer_code')],
            },
        ),
    ]
