# Generated by Django 5.2.17 on 2026-09-11 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='geocode_attempted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
