# Generated by Django 5.2.17 on 2026-09-11 23:40

import django.db.models.deletion
from django.db import migrations, models


def assign_default_project(apps, schema_editor):
    # Django's FKs are DEFERRABLE INITIALLY DEFERRED, so inserting a Project
    # would leave its tenant check pending until commit — and the deferred
    # `ALTER TABLE ... ADD CONSTRAINT ... REFERENCES projects_project` that
    # closes this migration then fails with "pending trigger events".
    schema_editor.execute('SET CONSTRAINTS ALL IMMEDIATE')
    Tenant = apps.get_model('accounts', 'Tenant')
    Project = apps.get_model('projects', 'Project')
    Customer = apps.get_model('customers', 'Customer')
    for tenant in Tenant.objects.all():
        project, _ = Project.objects.get_or_create(tenant=tenant, name='Default')
        Customer.objects.filter(tenant=tenant, project__isnull=True).update(project=project)


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_customer_geocode_attempted_at'),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customers', to='projects.project'),
        ),
        migrations.RunPython(assign_default_project, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='customer',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customers', to='projects.project'),
        ),
        migrations.RemoveConstraint(
            model_name='customer',
            name='unique_tenant_customer_code',
        ),
        migrations.AddConstraint(
            model_name='customer',
            constraint=models.UniqueConstraint(fields=('project', 'customer_code'), name='unique_project_customer_code'),
        ),
        migrations.RemoveIndex(
            model_name='customer',
            name='customer_tenant_state_idx',
        ),
        migrations.RemoveIndex(
            model_name='customer',
            name='customer_tenant_county_idx',
        ),
        migrations.RemoveIndex(
            model_name='customer',
            name='customer_tenant_city_idx',
        ),
        migrations.RemoveIndex(
            model_name='customer',
            name='customer_tenant_zip_idx',
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['project', 'state'], name='customer_project_state_idx'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['project', 'county'], name='customer_project_county_idx'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['project', 'city'], name='customer_project_city_idx'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['project', 'zipcode'], name='customer_project_zip_idx'),
        ),
    ]
