# Generated by Django 5.2.17 on 2026-09-11 23:40

import django.db.models.deletion
from django.db import migrations, models


def assign_default_project(apps, schema_editor):
    # See customers/0003: keep the Project insert from leaving a deferred FK
    # check pending, or the FK ALTER TABLE at the end of this migration fails.
    schema_editor.execute('SET CONSTRAINTS ALL IMMEDIATE')
    Tenant = apps.get_model('accounts', 'Tenant')
    Project = apps.get_model('projects', 'Project')
    Route = apps.get_model('routes', 'Route')
    for tenant in Tenant.objects.all():
        project, _ = Project.objects.get_or_create(tenant=tenant, name='Default')
        Route.objects.filter(tenant=tenant, project__isnull=True).update(project=project)


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
        ('routes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='routes', to='projects.project'),
        ),
        migrations.RunPython(assign_default_project, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='route',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routes', to='projects.project'),
        ),
    ]
