from config.env import env, validate_env

REQUIRED_ENV_VARS = ["GEOCODER_CLASS", "NOMINATIM_URL", "NOMINATIM_USER_AGENT"]
validate_env(REQUIRED_ENV_VARS)

GEOCODER_CLASS = env("GEOCODER_CLASS")
NOMINATIM_URL = env("NOMINATIM_URL")
NOMINATIM_USER_AGENT = env("NOMINATIM_USER_AGENT")
